BIN-1276 | Add the file transfer to I2C device over I3C project
binhollc/SupernovaController-Examples pull request #7
Opened 2024-08-26 18:56 UTC by Valentin-Otte

## Resolve:
[BIN-1276](https://focusuy.atlassian.net/browse/BIN-1276)

## Changes:
This PR adds the _file transfer to I2C device over I3C_ project to the Supernova Controller examples. This project aims to load a text file, save it into an I2C FRAM memory, read the I2C FRAM, and store the retrieved data into a new text file for content comparison. Communication with the I2C FRAM is achieved using I3C with legacy I2C device compatibility.

2024-08-27 16:43 UTC, Salonso1602 approved these changes
LGTM, I've left a minor comment but nothing too important

2024-08-27 16:43 UTC, Salonso1602 commented on file_transfer_to_I2C_device_over_I3C/i2c_file_transfer_example.ipynb
> +  }
This is an empty cell, consider removing it

2024-08-28 13:05 UTC, focus-martin requested changes
LGTM! However, I requested some minor changes.

2024-08-28 13:05 UTC, focus-martin commented on file_transfer_to_I2C_device_over_I3C/README.md
> +The objective of this project is to load a text file, save it into an I2C FRAM memory, read the I2C FRAM, and store the retrieved data into a new text file for content comparison. Communication with
Specify here that the I3C Private Write transfers are conveyed in 64-byte chunks, and I3C Private Read transfers are performed over 250-byte chunks. Because only the flow diagram of the write-phase indicates the length of the transfer, but not the read-phase diagram

2024-08-28 13:05 UTC, focus-martin commented on file_transfer_to_I2C_device_over_I3C/requirements.txt
> +supernovacontroller==1.4.0
Add the "minimum" FW version

2024-08-28 13:05 UTC, focus-martin commented on file_transfer_to_I2C_device_over_I3C/i2c_file_transfer_example.ipynb
> +    "command = f'code --diff {file1} {file2}'\n",
As far as I understood, this uses a VSCode extension, right? This [one](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-diff)? Am I right? 

If so, add a comments indicating that this extension is required.

2024-08-28 18:41 UTC, Valentin-Otte commented on file_transfer_to_I2C_device_over_I3C/i2c_file_transfer_example.ipynb
> +    "command = f'code --diff {file1} {file2}'\n",
It's a native feature of VS Code, so no extra extensions should be needed. However, the documentation will be updated to indicate that this works with VS Code.

2024-08-28 18:47 UTC, Valentin-Otte commented on file_transfer_to_I2C_device_over_I3C/requirements.txt
> +supernovacontroller==1.4.0
This is for pip to install the Python packages. The needed FW version is detailed in the notebook.

2024-08-29 12:04 UTC, focus-martin commented on file_transfer_to_I2C_device_over_I3C/requirements.txt
> +supernovacontroller==1.4.0
You're right!

2024-08-29 12:04 UTC, focus-martin commented on file_transfer_to_I2C_device_over_I3C/i2c_file_transfer_example.ipynb
> +    "command = f'code --diff {file1} {file2}'\n",
Ok, perfect. Thank you.

2024-08-29 12:06 UTC, focus-martin approved these changes
Well done Vale! It is great to have a new example of the Supernova Controller showcasing the use of I2C over I3C.

2024-08-29 12:34 UTC, merged